insert into airports (icao,flughafen_name)
values("EDAH","Heringsdorf"),
 ("EDDF", "Frankfurt am Main"),
 ("EDDK", "Köln/Bonn"),
 ("EDBC","Magdeburg-Chochstedt"), 
 ("EDBH", "Barth"), 
 ("EDBN", "Neubrandenburg"),
 ("EDDB", "Berlin-Schönefeld"),
 ("EDDC", "Dresden"),
 ("EDDE", "Erfurt-Weimar"),
 ("EDDG", "Münster-Osnabrück"),
 ("EDDH", "Hamburg"),
 ("EDDL", "Düsseldorf"),
 ("EDDM", "München"),
 ("EDDN", "Nürnberg"),
 ("EDDP", "Leipzig/Halle"),
 ("EDDR", "Saarbrücken"),
 ("EDDS", "Stuttgart"),
 ("EDDT", "Berlin-Tegel"),
 ("EDDV", "Hannover-Langenhagen"),
 ("EDDW", "Bremen"),
 ("EDFH", "Frankfurt-Hahn"),
 ("EDGS", "Siegerland"),
 ("EDHL", "Lübeck-Blankensee"),
 ("EDJA", "Memmmingen"),
 ("EDLP", "Paderborn-Lippstadt"),
 ("EDLV", "Niederrhein"),
 ("EDLW", "Dortmund"),
 ("EDMO", "Oberpfaffenhofen"),
 ("EDNY", "Friedrichshafen"),
 ("EDOP", "Schwerin-Parchim"),
 ("EDSB", "Karlsruhe/Baden-Baden"),
 ("EDTL", "Lahr"),
 ("EDVE", "Braunschweig-Wolfsburg"),
 ("EDVK", "Kassel-Calden"),
 ("EDXW", "Sylt"),
 ("ETMN", "Cuxhaven/Nordholz"),
 ("ETNL", "Rostock-Laage"),
 ("ETSI", "Ingolstadt/Manching");
 
 
 
 